#!/usr/bin/env Rscript
# =============================================================================
# USMCA Monthly Share Noise Diagnostic
# =============================================================================
#
# Compares monthly product-level USMCA shares against annual shares to assess
# noise levels. Helps determine whether monthly mode adds signal or just noise.
#
# Prerequisites:
#   - Annual file: resources/usmca_product_shares_{year}.csv
#   - Monthly diagnostic: resources/usmca_product_shares_{year}_monthly_diagnostic.csv
#     (generated by: Rscript src/download_usmca_dataweb.R --monthly --year 2025)
#
# Output: output/diagnostics/usmca_monthly_noise.csv
#
# Usage: Rscript scripts/usmca_monthly_noise_diagnostic.R
#        Rscript scripts/usmca_monthly_noise_diagnostic.R --year 2025
# =============================================================================

library(tidyverse)
library(here)

args <- commandArgs(trailingOnly = TRUE)
year <- if ('--year' %in% args) {
  as.integer(args[which(args == '--year') + 1])
} else {
  2025L
}

# --- Load data ---
monthly_path <- here('resources', paste0('usmca_product_shares_', year, '_monthly_diagnostic.csv'))
annual_path <- here('resources', paste0('usmca_product_shares_', year, '.csv'))

if (!file.exists(monthly_path)) {
  stop('Monthly diagnostic file not found: ', monthly_path, '\n',
       'Run: Rscript src/download_usmca_dataweb.R --monthly --year ', year)
}
if (!file.exists(annual_path)) {
  stop('Annual file not found: ', annual_path, '\n',
       'Run: Rscript src/download_usmca_dataweb.R --year ', year)
}

monthly <- read_csv(monthly_path, col_types = cols(
  month = col_integer(), hts10 = col_character(), cty_code = col_character(),
  usmca_share = col_double(), total_value = col_double(), usmca_value = col_double()
))
annual <- read_csv(annual_path, col_types = cols(
  hts10 = col_character(), cty_code = col_character(), usmca_share = col_double()
))

message('Loaded monthly diagnostic: ', nrow(monthly), ' rows (',
        n_distinct(monthly$month), ' months)')
message('Loaded annual shares: ', nrow(annual), ' product-country pairs')

# --- Per-product monthly statistics ---
product_stats <- monthly %>%
  group_by(hts10, cty_code) %>%
  summarise(
    n_months = n(),
    mean_share = mean(usmca_share),
    sd_share = sd(usmca_share),
    min_share = min(usmca_share),
    max_share = max(usmca_share),
    spread = max_share - min_share,
    cv = if_else(mean_share > 0, sd_share / mean_share, NA_real_),
    total_annual_value = sum(total_value),
    total_usmca_value = sum(usmca_value),
    .groups = 'drop'
  ) %>%
  left_join(annual %>% rename(annual_share = usmca_share), by = c('hts10', 'cty_code')) %>%
  mutate(
    annual_share = replace_na(annual_share, 0),
    mean_vs_annual_diff = mean_share - annual_share,
    hs2 = substr(hts10, 1, 2)
  )

# --- Flag noisy products ---
# CV > 0.5 = high relative volatility
# spread > 0.3 = big absolute swings
product_stats <- product_stats %>%
  mutate(
    noisy = (!is.na(cv) & cv > 0.5) | spread > 0.3,
    trade_bucket = case_when(
      total_annual_value >= 1e6 ~ 'large (>$1M)',
      total_annual_value >= 1e5 ~ 'medium ($100K-$1M)',
      total_annual_value >= 1e4 ~ 'small ($10K-$100K)',
      TRUE ~ 'micro (<$10K)'
    )
  )

# =============================================================================
# Summary output
# =============================================================================

message('\n', strrep('=', 60))
message('USMCA MONTHLY SHARE NOISE DIAGNOSTIC — ', year)
message(strrep('=', 60))

message('\n--- Overall ---')
message('  Products with monthly data: ', nrow(product_stats))
message('  Flagged as noisy: ', sum(product_stats$noisy, na.rm = TRUE),
        ' (', round(100 * mean(product_stats$noisy, na.rm = TRUE), 1), '%)')

# Noisy by trade size
noise_by_trade <- product_stats %>%
  group_by(trade_bucket) %>%
  summarise(
    n = n(),
    n_noisy = sum(noisy, na.rm = TRUE),
    pct_noisy = round(100 * n_noisy / n, 1),
    total_value = sum(total_annual_value),
    noisy_value = sum(total_annual_value[noisy], na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  mutate(pct_value_noisy = round(100 * noisy_value / total_value, 1))

message('\n--- Noise by trade size ---')
print(noise_by_trade, n = 10)

# Noise by HS2 chapter (top 10 noisiest)
noise_by_chapter <- product_stats %>%
  group_by(hs2) %>%
  summarise(
    n = n(),
    n_noisy = sum(noisy, na.rm = TRUE),
    pct_noisy = round(100 * n_noisy / n, 1),
    mean_cv = round(mean(cv, na.rm = TRUE), 3),
    mean_spread = round(mean(spread), 3),
    total_value = sum(total_annual_value),
    .groups = 'drop'
  ) %>%
  arrange(desc(pct_noisy))

message('\n--- Top 15 noisiest HS2 chapters ---')
print(noise_by_chapter %>% head(15), n = 15)

# Mean-monthly vs annual agreement
message('\n--- Monthly mean vs annual share agreement ---')
corr <- cor(product_stats$mean_share, product_stats$annual_share, use = 'complete.obs')
mae <- mean(abs(product_stats$mean_vs_annual_diff), na.rm = TRUE)
message('  Correlation: ', round(corr, 4))
message('  Mean absolute difference: ', round(mae, 4))
message('  Products with |diff| > 0.1: ',
        sum(abs(product_stats$mean_vs_annual_diff) > 0.1, na.rm = TRUE))
message('  Products with |diff| > 0.05: ',
        sum(abs(product_stats$mean_vs_annual_diff) > 0.05, na.rm = TRUE))

# Monthly aggregate shares (cross-check with usmca_monthly_summary.R)
message('\n--- Monthly aggregate shares (value-weighted) ---')
monthly_agg <- monthly %>%
  group_by(month, cty_code) %>%
  summarise(
    total = sum(total_value), usmca = sum(usmca_value),
    share = round(usmca / total * 100, 1), .groups = 'drop'
  )
for (i in seq_len(nrow(monthly_agg))) {
  r <- monthly_agg[i, ]
  cty <- if (r$cty_code == '1220') 'CA' else 'MX'
  cat(sprintf('  Month %02d  %s  %5.1f%%  ($%.1fB / $%.1fB)\n',
              r$month, cty, r$share, r$usmca / 1e6, r$total / 1e6))
}

# CV distribution
message('\n--- CV distribution (products with mean_share > 0) ---')
cv_vals <- product_stats$cv[!is.na(product_stats$cv)]
print(quantile(cv_vals, probs = c(0, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 1.0)))

# --- Save ---
out_dir <- here('output', 'diagnostics')
if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

out_path <- file.path(out_dir, paste0('usmca_monthly_noise_', year, '.csv'))
write_csv(product_stats %>% arrange(desc(cv)), out_path)
message('\nSaved diagnostic output: ', out_path, ' (', nrow(product_stats), ' rows)')
